### PR TITLE
update! TextureBuffer using gpu_resize!

### PR DESCRIPTION
**Pull request by skleinbo**
Dynamically change number of particles in a meshscatter plot.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
I guess we can merge this, if we add a couple of tests for this here:
https://github.com/JuliaPlots/GLMakie.jl/blob/master/test/glmakie_tests.jl#L23

**Comment by skleinbo** [comment]
Great. What kind of tests do you think are needed? 

Something like
https://gist.github.com/skleinbo/2917b0418a184d245e41f4dac4f21ef7 maybe?

**Comment by SimonDanisch** [comment]
Almost! How about:
```julia
    # Test for resizing of TextureBuffer
    @cell "Dynamically adjusting number of particles in a meshscatter" [meshscatter] begin

        posb = Node(rand(Point3f0, 2))
        rotb = Node(rand(Vec3f0, 2))
        colorb = Node(rand(RGBf0, 2))
        sizeb = Node(1/2*rand(2))

        makenew = Node(1)
        on(makenew) do i
            pos[] = rand(Point3f0, i)
            rot[] = rand(Vec3f0, i)
            color[] = rand(RGB, i)
            size[] = 1/2*rand(i)
        end

        scene = meshscatter(pos,
            rotations=rot,
            color=color,
            markersize=size,
            limits=FRect3D(Point3(0), Point3(1))
        )
        
        record(scene, @replace_with_a_path(mp4), [10, 5, 100, 60, 177]) do i
            makenew[] = makenew[] + 1
        end
    end
```

**Comment by skleinbo** [comment]
Right, making it reproducible is not a bad idea for a test :)

**Comment by SimonDanisch** [comment]
Thank you! I will merge this in: https://github.com/JuliaPlots/GLMakie.jl/pull/110

**Pull request closed without merging**
