### PR TITLE
Fix for pick(::Screen, ::IRect2D) always throwing an error

### PR DESCRIPTION
**Pull request by kragol**
This is a proposed fix for JuliaPlots/Makie.jl#704

There were actually two problems in `pick(screen::Screen, rect::IRect2D)`

Firstly it appears that `pick(screen::Screen, rect::IRect2D)` was missing the following two lines that appear in other `pick` / `pick_native` functions in screen.jl.
```julia
    fb = screen.framebuffer
    glBindFramebuffer(GL_FRAMEBUFFER, fb.id[1])
```

Secondly, with those added, the pick function works but only if all points within the `rect` are actually on a plot object. Otherwise, the following error is thrown
```julia
ERROR: KeyError: key 65535 not found
Stacktrace:
 [1] getindex at ./dict.jl:467 [inlined]
 [2] #170 at /home/.../.julia/dev/GLMakie/src/screen.jl:471 [inlined]
 [3] iterate at ./generator.jl:47 [inlined]
 [4] _collect(::Array{GLMakie.SelectionID{Int64},1}, ::Base.Generator{Array{GLMakie.SelectionID{Int64},1},GLMakie.var"#170#171"{GLMakie.Screen}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at ./array.jl:699
 [5] collect_similar(::Array{GLMakie.SelectionID{Int64},1}, ::Base.Generator{Array{GLMakie.SelectionID{Int64},1},GLMakie.var"#170#171"{GLMakie.Screen}}) at ./array.jl:628
 [6] map(::Function, ::Array{GLMakie.SelectionID{Int64},1}) at ./abstractarray.jl:2162
 [7] pick(::GLMakie.Screen, ::GeometryBasics.HyperRectangle{2,Int64}) at /home/.../.julia/dev/GLMakie/src/screen.jl:470
 [8] top-level scope at REPL[21]:1
 [9] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
```
65535 is the code returned in the `sid` variable to indicate that there is no plot object at the given coordinates. Those values must therefore be filtered out to get a list of the plot objects in the rect.

IMPORTANT: This PR conflicts with JuliaPlots/GLMakie.jl#126. If the latter is merged first then this PR needs to modified as the 65535 code should be replaced with 0x3f800000.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Thanks! Do you have some minimal tests for this that we could add?

**Comment by kragol** [comment]
Thank you! Yeah, I can try and write some basic tests. I'll try and have a go at it this week hopefully.

BTW, writing such tests (especially related to PR#126) would be a lot easier if I knew how to compute the on screen position (in pixel coordinates) of a plot object. There is the `to_world` function to get from screen position to "data coordinates" but I could not find the reverse function (which is basically done somewhere in the rendering pipeline). Is there by any chance a convenience function in `AbstractPlotting` that would do the reverse of `to_world`? This would also be quite helpful for other purposes: I kind of wanted that function before when writing code to display a popup (a datatip bascially) that is positioned (x,y) pixels away from a data point (in a scatter plot).

**Comment by SimonDanisch** [comment]
Cool!
I think this should do what you want: https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/camera/projection_math.jl#L317

**Comment by kragol** [comment]
Excellent!

**Comment by kragol** [comment]
I submitted some tests as #133. Currently they don't work when run as part of the test suite. I don't know why.

**Pull request merged**
