### PR TITLE
Change stencil to scissor test in SSAO

### PR DESCRIPTION
**Pull request by ffreyer**
This pr swaps out the stencil test for a scissor test, which works regardless of `clear`. This does have some other potential issues though. The ssao postprocessor should only run once per pixel. With the scissor test multiple overlapping scenes could be running it, making things darker than they should be. To avoid this somewhat I only allowed leaf scenes (i.e. no children) to run SSAO. This means that SSAO will be wrong if a scene with children has a different projection matrix than it's children, or if its children cover less area. (I think this should be very rare?)

See also: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/624
I'm pretty sure https://github.com/JuliaPlots/AbstractPlotting.jl/pull/649 breaks SSAO again (it uses `clear = false`) which this pr should fix.

### CODE REVIEW

**Comment by ffreyer** [comment]
Yup it does break SSAO: (more or less the example from docs/lighting)
Screenshot from 2021-04-03 18-10-25

With this pr:
Screenshot from 2021-04-03 18-09-07

**Comment by ffreyer** [comment]
This will also be useful for https://github.com/JuliaPlots/AbstractPlotting.jl/pull/677 because it allows us to use `clear = false` in `LScene` and `Axis3`, which in turn allows information to be visualized in the screen space scene of the parent figure.

**Comment by SimonDanisch** [comment]
Hm, I'm pretty sure i had pretty important reasons for using stencil tests, since they're much more complicated and the initial version used scissor tests... I need to try to remember the reason before we can merge this :D

**Comment by ffreyer** [comment]
This is just the ssao postprocessing, not general rendering (i.e. not any plot rendering). I set it up with the stencil buffer originally, see https://github.com/JuliaPlots/GLMakie.jl/pull/97

**Comment by SimonDanisch** [comment]
Oooh, the code looked so similar to the window rendering code :D I see... Ok, lets merge this then!

**Pull request merged**
